### ISSUE TITLE
deploy:install_dependencies doesn't download the WP Core

### ISSUE THREAD

**Issue by jason-murray** [iandunn/regolith#2]
In deploy:shared an empty /web/wordpress folder is created.

This is before deploy:install_dependencies where install_dependencies.sh checks and conditionally installs core based on the existence of the /web/wordpress folder. Because of the previous task creating the folder to make it available to symlink in to shared, core is never installed.

I'm not 100% sure why web/wordpress is included as a shared folder in `$other_shared` around line 55 in regolith-recipe.php.  It could be removed from here if not needed to solve the issue, or install_dependancies.sh can be modified to check for the presence of another folder inside /web/wordpress such as wp-admin as the deploy:shared task is just making an empty folder.

**Comment by jason-murray** [comment]
I'm not certain I'm seeing normal behaviour here, as all the lines involved were part of the initial commit, and I suppose it must have worked at some stage?! 😛

**Comment by iandunn** [comment]
10096e89a510b8cd59eba9b1488ca20c09669702 removed Deployer in favor of a simple shell script and `git pull`, so there's no longer a `shared` folder.

That might not have solved the issue, but it's worth re-testing with the latest if you're still running into this.

**Comment by iandunn** [comment]
Actually, I took a second look at #7 and it seems like a good idea regardless, and shouldn't have any side-effects, so I just went ahead and merged it. Thanks!
