### ISSUE TITLE
Update to Deployer v5 and change docs

### ISSUE THREAD

**Issue by jason-murray** [iandunn/regolith#8]
Deployer 5 is now using "hosts" instead of servers.  It also now supports relative symlinks but not in a great way as it just checks if it can use `ln --relative` as far as I can tell.  The current regolith implementation of relative symlinks is better in my view as it works on more shared hosts.

Also the Deployer wrapper included with regolith tripped me up a bit as it uses /usr/bin/php all the time, whereas I had my path set to use my MAMP php and its php.ini . Also it seems Deployer likes to use dep as the binary name and v5 can be called anywhere in the project so there may not be much need for the wrapper anymore.

I am working on the move to v5 and will probably put a PR in.

**Comment by iandunn** [comment]
10096e89a510b8cd59eba9b1488ca20c09669702 removed Deployer in favor of a simple shell script that uses `git pull` to update production.

In hindsight, Deployer was cool, but [overkill for this kind of project](https://markjaquith.wordpress.com/2018/01/30/simple-wordpress-deploys-using-git/), and created maintenance headaches.
